# Site settings
title: phreq's dark little crib  
description: > # this means to ignore newlines until "baseurl:"
  All the music of my life, in one place.
url: "https://phreq.neocities.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: pretty

exclude:
  - urban.gemspec
  - LICENSE
